### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mentos1386** [grieve/webpack-glsl-loader#2]
Hey, i was having a problem using this with typescript.

When i tried to do:
```
import someShader from './someShader.glsl';
```

It would complain that module doesn't exists.

The solution i found is that you can add type definitions like [this](https://github.com/mentos1386/ts-shader-loader/blob/master/lib/index.d.ts), to make it stop complaining.

**Comment by grieve** [comment]
Thanks @mentos1386, a response to this is a long time coming, sorry about that. I recommend anyone using Typescript, to use your fork https://github.com/mentos1386/ts-shader-loader as it has been maintained much more recently :)
