### ISSUE TITLE
Share fragments code

### ISSUE THREAD

**Issue by nuthinking** [grieve/webpack-glsl-loader#3]
Is there a way to include some code on multiple fragments so that some logic stays in one place? I believe sometimes I've seen using `#include` for example, perhaps to include functions. Thanks!

**Comment by turboMaCk** [comment]
There is a section in README https://github.com/grieve/webpack-glsl-loader#example

But it's super confusing. It gives an example:

> I can have that shader include other .glsl files inline, like so:
> ```
> #include "./includes/perlin-noise.glsl";
> ```

note __the `.glsl` extension__ in example and than it continues saying:

> N.B. all imports within .glsl __files exclude the file extension__ and are relative to the file doing the importing. :exploding_head: 

I tried both but neither works.

**Comment by turboMaCk** [comment]
I expect the reason is that https://github.com/grieve/webpack-glsl-loader/pull/6 was never released
